-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 19:30:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pain_diairy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pain_diairy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pain_diairy` DEFAULT CHARACTER SET utf8 ;
USE `pain_diairy` ;

-- -----------------------------------------------------
-- Table `pain_diairy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_diairy`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_diairy`.`symptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_diairy`.`symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_diairy`.`user_symptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_diairy`.`user_symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `symptom_id` INT NOT NULL,
  `pain_level` INT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_has_symptom_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pain_diairy`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_symptom_symptom1`
    FOREIGN KEY (`symptom_id`)
    REFERENCES `pain_diairy`.`symptom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pain_diairy` ;

-- -----------------------------------------------------
-- Placeholder table for view `pain_diairy`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_diairy`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `pain_diairy`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pain_diairy`.`view1`;
USE `pain_diairy`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
